CREATE TABLE IF NOT EXISTS "ApprovalDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" character varying(200) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_ApprovalDocuments_Status"
        CHECK ("Status" IN ('Pending', 'Approved', 'Rejected'))
);

CREATE INDEX IF NOT EXISTS "IX_ApprovalDocuments_Status"
    ON "ApprovalDocuments" ("Status");

CREATE TABLE IF NOT EXISTS "ApprovalDecisions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Action" character varying(20) NOT NULL,
    "Reason" character varying(1000) NOT NULL,
    "DecidedBy" character varying(100) NOT NULL,
    "DecidedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "CK_ApprovalDecisions_Action"
        CHECK ("Action" IN ('Approved', 'Rejected')),
    CONSTRAINT "CK_ApprovalDecisions_Reason_NotBlank"
        CHECK (length(btrim("Reason")) > 0)
);

CREATE INDEX IF NOT EXISTS "IX_ApprovalDecisions_DecidedAt"
    ON "ApprovalDecisions" ("DecidedAt");

CREATE TABLE IF NOT EXISTS "ApprovalDecisionItems" (
    "DecisionId" integer NOT NULL,
    "DocumentId" integer NOT NULL,
    CONSTRAINT "PK_ApprovalDecisionItems"
        PRIMARY KEY ("DecisionId", "DocumentId"),
    CONSTRAINT "FK_ApprovalDecisionItems_ApprovalDecisions_DecisionId"
        FOREIGN KEY ("DecisionId") REFERENCES "ApprovalDecisions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApprovalDecisionItems_ApprovalDocuments_DocumentId"
        FOREIGN KEY ("DocumentId") REFERENCES "ApprovalDocuments" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ApprovalDecisionItems_DocumentId"
    ON "ApprovalDecisionItems" ("DocumentId");

INSERT INTO "ApprovalDocuments" ("Id", "Title", "Status", "CreatedAt") VALUES
(1, 'ใบขออนุมัติเบิกจ่ายค่าเดินทางเข้าพบลูกค้า จ.เชียงใหม่', 'Pending', now() - interval '1 day'),
(2, 'ใบสั่งซื้อโน้ตบุ๊กสำหรับพนักงานใหม่ 3 เครื่อง', 'Approved', now() - interval '2 days'),
(3, 'แบบขอลาพักร้อนล่วงหน้า 10 วัน เดือนตุลาคม', 'Rejected', now() - interval '3 days'),
(4, 'ใบขออนุมัติจ้างพนักงานประจำตำแหน่ง Developer 1 อัตรา', 'Pending', now() - interval '4 days'),
(5, 'ใบเบิกค่าอบรมออนไลน์หลักสูตร Azure Fundamentals', 'Approved', now() - interval '5 days'),
(6, 'แบบขอเปลี่ยนเวลาทำงานเป็น WFH 3 วันต่อสัปดาห์', 'Rejected', now() - interval '6 days'),
(7, 'ใบขออนุมัติงบจัดกิจกรรมส่งท้ายปีเก่าแผนก IT', 'Pending', now() - interval '7 days'),
(8, 'ใบสั่งซื้อ license ซอฟต์แวร์ Figma รายปี 5 ที่นั่ง', 'Pending', now() - interval '8 days'),
(9, 'ใบขออนุมัติเบิกค่าโทรศัพท์ติดต่องานราชการต่างจังหวัด', 'Pending', now() - interval '9 days'),
(10, 'แบบขอซ่อมแซมเครื่องปรับอากาศห้อง Server ชั้น 3', 'Pending', now() - interval '10 days');

INSERT INTO "ApprovalDecisions" ("Id", "Action", "Reason", "DecidedBy", "DecidedAt") VALUES
(1, 'Approved', 'อยู่ในงบประมาณที่อนุมัติไว้ของไตรมาสนี้', 'admin', now() - interval '2 days' + interval '3 hours'),
(2, 'Rejected', 'ช่วงดังกล่าวมีงานประจำปี กรุณาเลื่อนเป็นเดือนพฤศจิกายน', 'admin', now() - interval '3 days' + interval '3 hours'),
(3, 'Approved', 'เป็นไปตามแผนพัฒนาบุคลากรประจำปี', 'admin', now() - interval '5 days' + interval '3 hours'),
(4, 'Rejected', 'ตำแหน่งงานต้องประจำที่ออฟฟิศตามนโยบายบริษัท', 'admin', now() - interval '6 days' + interval '3 hours');

INSERT INTO "ApprovalDecisionItems" ("DecisionId", "DocumentId") VALUES
(1, 2),
(2, 3),
(3, 5),
(4, 6);

SELECT setval(pg_get_serial_sequence('"ApprovalDocuments"', 'Id'), 10);
SELECT setval(pg_get_serial_sequence('"ApprovalDecisions"', 'Id'), 4);
